FootballMeetingRoom/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FootballMeetingRoom.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

FootballMeetingRoom/Controllers/StrategyRoomController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FootballMeetingRoom.Controllers
{
    //[Authorize]
    public class StrategyRoomController : Controller
    {
        // GET: StrategyRoom
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Board()
        {
            return View();
        }
    }
}

FootballMeetingRoom/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

FootballMeetingRoom/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

FootballMeetingRoom/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home";
}

<div class="jumbotron">
    <h1>Football Meeting Room</h1>
    <p class="lead">Meet up with your team members anytime. <span style="color:orange">Understanding each other</span> leads your team to <span style="color:lightseagreen">victoreis</span>.</p>
    <p>@Html.ActionLink("Learn more »", "About", "Home", new { }, new { @class = "btn btn-primary btn-lg" })</p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            Register with your Facebook account, then you're in. (This is not available yet.)
        </p>
        <p>@* @Html.ActionLink("Log in", "Login", "Account", routeValues: null, htmlAttributes: new { @class = "btn btn-default" }) *@</p>
    </div>
    <div class="col-md-4">
        <h2>Strategy Room</h2>
        <p></p>
        <p>@Html.ActionLink("Strategy Room »", "Index", "StrategyRoom", new { }, new { @class = "btn btn-default" })</p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>